# Generated by Django 5.0.6 on 2024-06-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ބަޔޯ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pfps', verbose_name='ޕްރޮފައިލް ފޮޓޯ'),
        ),
    ]
