# Generated by Django 5.0.6 on 2024-06-14 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 21, 35, 10, 254597, tzinfo=datetime.timezone.utc)),
        ),
    ]
