# Generated by Django 5.0.6 on 2024-06-16 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 16, 18, 30, 43, 304088, tzinfo=datetime.timezone.utc)),
        ),
    ]
