# Generated by Django 5.0.6 on 2024-06-17 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 0, 50, 25, 987272, tzinfo=datetime.timezone.utc)),
        ),
    ]
