# Generated by Django 5.0.6 on 2024-08-19 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_date_posted_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 19, 16, 44, 11, 493040, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 19, 16, 44, 11, 421505, tzinfo=datetime.timezone.utc)),
        ),
    ]
